# Config Interface 
[[ifaces]]
name = "eth0"
zone_type = "wan"

[[ifaces]]
name = "br_lan"
create_dev_type = "bridge"
zone_type = "lan"

[[ifaces]]
name = "pc1"
controller_name = "br_lan"

[[ifaces]]
name = "pc2"
controller_name = "br_lan"

# Config IP
[[ipconfigs]]
iface_name = "eth0"
enable = true

[ipconfigs.ip_model]
t = "static"
ipv4 = "172.123.0.2"
ipv4_mask = 16

# Config NAT
[[nats]]
iface_name = "eth0"
enable = true

# Config IP ( You don’t need to put similar configurations together )
[[dhcpv4_services]]
iface_name = "br_lan"
enable = true

[dhcpv4_services.config]
server_ip_addr = "192.168.5.1"
ip_range_start = "192.168.5.100"
ip_range_end = "192.168.5.200"
network_mask = 24

# LAN 绑定的 MAC 地址
mac_binding_records = [
    { mac = "00:11:22:33:44:55", ip = "192.168.5.50" },
    { mac = "aa:bb:cc:dd:ee:ff", ip = "192.168.5.51" },
]


[[dns_rules]]
name = "default rule"
index = 1000
enable = true
redirection = false
# An empty 'source' matches all domains.
# Therefore, the default rule's index must be higher than those of more specific rules,
# ensuring that specific rules (with lower index values) are matched first.
source = []

[[dns_rules]]
name = "example"
index = 200
enable = true
redirection = false
source = [
    { t = "geokey", key = "geo_key_value" },
    { t = "config", match_type = "plain", value = "example.com" },
]


[[dns_rules]]
name = "just for google.com"
index = 500
enable = true
redirection = false
source = [{ t = "config", match_type = "plain", value = "google.com" }]
